server.port: 9511

management:
  server.port: 9512
  health:
    defaults.enabled: true
    diskspace.enabled: false
  endpoints:
    web:
      base-path: /actuator
      exposure.include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: never
    auditevents.enabled: false
  metrics:
    tags:
      application: ${spring.application.name}
    enable.jvm: true
    enable.jvm.gc.pause: true
    enable.jvm.memory: true
    enable.jvm.threads: true
    enable.process: true
    enable.process.files: true
    enable.http: true
    enable.http.server.requests: true
    enable.logback: true
    enable.system: true
    export:
      prometheus:
        enabled: true

spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/geofencing

---
spring:
  profiles: local
  zipkin:
    enabled: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/trips?maxPoolSize=1
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration

---
spring:
  profiles: no-consul
  application:
    name: bench-marking
  zipkin:
    enabled: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/trips?maxPoolSize=1
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
