server.port: 9566

management:
  server.port: 9567
  health:
    defaults.enabled: true
    diskspace.enabled: false
  endpoints:
    web:
      base-path: /actuator
      exposure.include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: never
    auditevents.enabled: false
  metrics:
    tags:
      application: ${spring.application.name}
    enable.jvm: false
    enable.jvm.gc.pause: true
    enable.jvm.memory: true
    enable.jvm.threads: true
    enable.process: false
    enable.process.files: true
    enable.http: false
    enable.http.server.requests: true
    enable.logback: false
    enable.system: false
    export:
      prometheus:
        enabled: true

spring:
  datasource:
    initialization-mode: always

  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      key-serializer: org.springframework.kafka.support.serializer.StringOrBytesSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        - spring.json.type.mapping: MoverLocationUpdate:statefull.geofencing.faas.common.dto.MoverLocationUpdate



