version: '3.7'
services:
  consul-server:
    network_mode: host
    container_name: "consul-server"
    hostname: consul-server
    image: consul:latest
    command: "agent -server -ui -node=server-1 -advertise=${SERVER1_IP} -bootstrap-expect=1"
    ports:
      - "8300:8300/tcp"
      - "8300:8300/udp"
      - "8301:8301/tcp"
      - "8301:8301/udp"
      - "8302:8302/tcp"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600/udp"
      - "8600:8600/tcp"
      - "7946:7946/udp"
      - "7946:7946/tcp"

  zookeeper:
    container_name: zookeeper1
    network_mode: host
    hostname: zookeeper
#    container_name: zookeeper
    image: zookeeper
    restart: always
    ports:
      - "2181:2181"
      - "3888:3888"
      - "2888:2888"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=${SERVER2_IP}:2888:3888;2181

  kafka:
    container_name: kafka1
    network_mode: host
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: ${SERVER1_IP}:2181,${SERVER2_IP}:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://${SERVER1_IP}:9094
      KAFKA_LISTENERS: OUTSIDE://${SERVER1_IP}:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
      JMX_PORT: 9997
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
