version: '3.7'
services:
  consul-client:
    network_mode: host
    container_name: "consul-client"
    hostname: consul-client
    image: consul:latest
    command: "agent -node=client-1 -join=192.168.1.24 -advertise=192.168.1.12"
    ports:
      - '8500:8500'
      - '8600:8600'
      - '8301:8301'
      - '8300:8300'
