version: '3.7'
services:
  consul-server:
    network_mode: bridge
    container_name: "consul-server"
    hostname: consul-server
    image: consul:latest
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1"
    ports:
      - '8500:8500'
      - '8600:8600'
      - '8301:8301'
