version: "3.7"
services:
  consul-client:
    network_mode: bridge
    container_name: "consul-client"
    hostname: consul-client
    image: consul:latest
    command: "agent -node=client-1 -join=${SERVER1_IP} -advertise=${SERVER2_IP}"
    ports:
      - "8300:8300/tcp"
      - "8300:8300/udp"
      - "8301:8301/tcp"
      - "8301:8301/udp"
      - "8302:8302/tcp"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600/udp"
      - "8600:8600/tcp"
      - "7946:7946/udp"
      - "7946:7946/tcp"

  zookeeper:
    network_mode: bridge
    hostname: zookeeper
#    container_name: zookeeper
    image: zookeeper
    restart: always
    ports:
      - "2181:2181"
      - "3888:3888"
      - "2888:2888"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=${SERVER1_IP}:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181

  kafka:
    hostname: kafka
    network_mode: host
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: ${SERVER1_IP}:2181,${SERVER2_IP}:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092, OUTSIDE://${SERVER2_IP}:9094
      KAFKA_LISTENERS: INSIDE://kafka:9092, OUTSIDE://${SERVER2_IP}:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
      KAFKA_ADVERTISED_PORT: 9094
      JMX_PORT: 9997
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock