version: "3.7"
services:
  consul-client:
    network_mode: host
    container_name: "consul-client"
    hostname: consul-client
    image: consul:latest
    command: "agent -node=client-1 -join=192.168.1.24 -advertise=192.168.1.24"
    ports:
      - "8300:8300/tcp"
      - "8300:8300/udp"
      - "8301:8301/tcp"
      - "8301:8301/udp"
      - "8302:8302/tcp"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600/udp"
      - "8600:8600/tcp"
