version: '3.7'
services:
  consul-server:
    network_mode: host
    container_name: "consul-server"
    hostname: consul-server
    image: consul:latest
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -advertise=192.168.1.24"
    expose:
      - '8300'
      - '8500'
      - '8600'
      - '8301'
    ports:
      - '8500:8500'
      - '8600:8600'
      - '8301:8301'
      - '8300:8300'
