version: '3.7'
services:
  consul-server:
    network_mode: host
    container_name: "consul-server"
    hostname: consul-server
    image: consul:latest
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -bind=192.168.1.24"
    ports:
      - "8300:8300"
      - "8301:8301/tcp"
      - "8301:8301/udp"
      - "8302:8302/tcp"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
