scrape_configs:
  - job_name: 'consul_registered_services'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    consul_sd_configs:
      - server: '192.168.1.24:8500'
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: job

      # Hide Consul from the targets list
      - source_labels: [ __meta_consul_service ]
        regex: '(^consul)'
        target_label: job
        action: drop
